services:
  google_dorks_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: google_dorks-container
    env_file:
      - .env
    ports:
      - "8001:8000"

  dns_nmap_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dns_nmap-container
    env_file:
      - .env
    ports:
      - "8002:8000"

  deepseek_service:
    build: .
    image: deepseek-api
    container_name: deepseek-container
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8003:8000"
    restart: unless-stopped    